{% set name = "azure-keyvault-keys" %}
{% set version = "4.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 08632dcd6ece28657204e9a256ad64369fe2b0e385ed43349f932f007d89f774

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - azure-common ~=1.1
    - azure-core <2.0.0,>=1.29.5
    - cryptography >=2.1.4
    - isodate >=0.6.1
    - typing-extensions >=4.0.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - azure.keyvault.keys
    - azure.keyvault.keys.aio
    - azure.keyvault.keys.crypto
    - azure.keyvault.keys.crypto.aio

about:
  home: https://docs.microsoft.com/en-au/azure/key-vault/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Azure Key Vault Keys client library for Python
  doc_url: https://azuresdkdocs.blob.core.windows.net/$web/python/azure-keyvault-keys/latest/azure.keyvault.keys.html
  dev_url: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/keyvault/azure-keyvault-keys

extra:
  recipe-maintainers:
    - dhirschfeld
