{% set name = "azure-keyvault-keys" %}
{% set version = "4.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 6c0bb2f783202a34a3e5ec74866e6212e591ac7124f03b9669d1b09b68224bc4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - azure-common ~=1.1
    - azure-core >=1.24.0,<2.0.0
    - cryptography >=2.1.4
    - isodate >=0.6.1
    - typing-extensions >=4.0.1

test:
  imports:
    - azure.keyvault.keys
    - azure.keyvault.keys.aio
    - azure.keyvault.keys.crypto
    - azure.keyvault.keys.crypto.aio

about:
  home: https://docs.microsoft.com/en-au/azure/key-vault/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Azure Key Vault Keys client library for Python
  doc_url: https://azuresdkdocs.blob.core.windows.net/$web/python/azure-keyvault-keys/latest/azure.keyvault.keys.html
  dev_url: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/keyvault/azure-keyvault-keys

extra:
  recipe-maintainers:
    - dhirschfeld
