{% set name = "azure-keyvault-keys" %}
{% set version = "4.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 511206ae90aec1726a4d6ff5a92d754bd0c0f1e8751891368d30fb70b62955f1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - typing_extensions >=4.0.1
    - python >=3.7
    - azure-common ~=1.1
    - azure-core >=1.31.0
    - cryptography >=2.1.4
    - isodate >=0.6.1
    - typing-extensions >=4.0.1

test:
  imports:
    - azure.keyvault.keys
    - azure.keyvault.keys.aio
    - azure.keyvault.keys.crypto
    - azure.keyvault.keys.crypto.aio

about:
  home: https://docs.microsoft.com/en-au/azure/key-vault/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Azure Key Vault Keys client library for Python
  doc_url: https://azuresdkdocs.blob.core.windows.net/$web/python/azure-keyvault-keys/latest/azure.keyvault.keys.html
  dev_url: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/keyvault/azure-keyvault-keys

extra:
  recipe-maintainers:
    - dhirschfeld
