schema_version: 1

context:
  name: azure-keyvault-keys
  version: 4.9.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 08632dcd6ece28657204e9a256ad64369fe2b0e385ed43349f932f007d89f774

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - azure-core >=1.31.0
    - cryptography >=2.1.4
    - isodate >=0.6.1
    - typing-extensions >=4.0.1

tests:
  - python:
      imports:
        - azure.keyvault.keys
        - azure.keyvault.keys.aio
        - azure.keyvault.keys.crypto
        - azure.keyvault.keys.crypto.aio
      python_version: ${{ python_min }}.*
about:
  license: MIT
  license_file: LICENSE.txt
  summary: Azure Key Vault Keys client library for Python
  homepage: https://docs.microsoft.com/en-au/azure/key-vault/
  repository: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/keyvault/azure-keyvault-keys
  documentation: https://azuresdkdocs.blob.core.windows.net/$web/python/azure-keyvault-keys/latest/azure.keyvault.keys.html

extra:
  recipe-maintainers:
    - dhirschfeld
